import React, { useState } from "react";
import { CurrentPage } from "../../App";
import "../../styles/informationPopUp.css";
import infoIcon from "../../assets/icons/helper-icons/info.svg";
import closeIcon from "../../assets/icons/helper-icons/close.svg";

interface InformationProps {
  currentPage: CurrentPage;
}

function InformationPopUp({ currentPage }: InformationProps) {
  const [isDisplayed, setDisplayed] = useState<boolean>(false);
  const changePopUpState = () => {
    setDisplayed((x) => !x);
  };

  const infoIconImage = (
    <img
      src={infoIcon}
      className="info-icon"
      alt="sth"
      onClick={changePopUpState}
    />
  );
  const closeIconImage = (
    <img
      src={closeIcon}
      className="close-icon"
      alt="sth"
      onClick={changePopUpState}
    />
  );

  if (isDisplayed) {
    return (
      <div>
        <div className="info-container">
          <div className="info-container-title">
            {getInfoTitle(currentPage.currentPage)}
          </div>
          <div className="info-text">
            {getInfoExplanation(currentPage.currentPage)}
          </div>
          {closeIconImage}
        </div>
        {infoIconImage}
      </div>
    );
  } else return infoIconImage;
}

function getInfoExplanation(page: string) {
  switch (page) {
    case "anomalyList":
      return `
       The Anomaly List displays real-time locations of vessels on a map. Each entry in the scrollable 
       list includes the vessel's type (represented by an icon), the last three digits of the vessel's ID,
       its current anomaly score, and the time since the most recent AIS signal. You can click 
       on an entry for more detailed information. Also, once the entry is clicked, a corresponding
       ship is centered on the map. Moreover, by clicking the filter icon, you can change
       the anomaly score threshold to filter out vessels with scores below the threshold.
       Lastly, click the close button or the ship icon in the menu to exit the Anomaly List.
        `;
    case "objectDetails":
      return `
        The Object Details window displays real-time information for a specific vessel.
        The ship's ID is shown at the top. Below the ID, you can choose the 
        type of information you want to see by selecting from the menu. You can 
        view the current Anomaly Information data, current AIS data, all notifications
        related to the displayed vessel, and an interactive plot showing the vessel's
        anomaly score over time.

        Additionally, once the information was displayed, a vessel that corresponds to the displayed 
        information was centered in a map, and its past trajectory displayed. To exit the detailed 
        information window, click the arrow in the top-left corner.
        `;
    case "notificationList":
      return `
      The Notification List window displays a history of all notifications that have been
      sent. A notification is sent when a vessel becomes anomalous, meaning its anomaly
      score exceeds a specified threshold. Each entry in the scrollable list corresponds
      to a particular notification and contains, from left to right, a visual indicator
      of whether the notification has been read (orange bells means unread, white bells
      means read), the type of vessel that received the notification (indicated by an icon),
      the last three digits of its ID, and the time and date when the notification was received.

      Clicking on a notification provides more detailed information about it, centers the 
      corresponding ship on the map, and automatically marks the notification as read. 
      Additionally, all notifications can be marked as read by clicking the check button 
      in the top right corner. Finally, the notification list can be closed by clicking the 
      close button in the top left corner or a bell icon in the menu list.
      `;
    case "notificationDetails":
      return `
      The Notification Details window displays information about a specific notification. 
      At the top, you can see the ID of the notification and right below it, the ship's ID is shown. 
      Below this, there is a two-choice menu. By clicking on the desired option, you can view either the 
      anomaly information corresponding to the ship's anomaly at the time the notification was sent, or 
      view the AIS information at the time of the notification.

      To exit the Notification Details window, you can click on the arrow in the top-left corner.
      `;
    case "settings":
      return `
      In the future, a list of settings should be displayed here.
      `;
    case "errors":
      return `
      The Error List displays all error notifications generated by the system during
      execution. This list is for internal use only and provides information about
      issues within the system. The notification list contains three types of entries:
      errors (marked with a red icon), warnings (marked with a yellow icon), and 
      information (marked with an information icon). Errors are the most critical, 
      indicating issues that require immediate attention. Warnings are less severe 
      and are triggered by unexpected events that are not highly detrimental to the
      system. Information notifications provide useful information for the operator,
      such as when the server returns an empty list of ships.

      Each entry in the scrollable list of notifications includes, from left to 
      right, an icon corresponding to the type of error or notification, a brief
      description, and a bin icon that, when clicked, deletes the notification.
      Clicking on an entry marks it as read. Additionally, all notifications 
      can be marked as read by clicking a button in the top-right corner. 
      Finally, the error list window can be closed by clicking the exit button 
      in the top-left corner, or a corresponding warning icon in the menu.
      `;
    case "none":
      return `
      The map displays real-time ship locations based on their AIS data. Each ship's 
      color indicates its anomaly score, with greener colors representing less 
      anomalous ships and redder colors representing more anomalous ships. You 
      can use the mouse to zoom in and move around the map. Clicking on a ship's 
      visual indicator will provide more detailed information about its anomaly 
      score, AIS data, and notifications specific to that ship.

      Additionally, the clickable menu on the right-hand side includes the following 
      options from top to bottom: full anomaly list of all ships, notification history, 
      settings, and application errors.
      
      Finally, brief information about a ship is displayed when hovering the mouse over the visual indicator.
      `;
    default: {
      return "";
    }
  }
}

function getInfoTitle(page: string) {
  switch (page) {
    case "anomalyList":
      return "Anomaly List Information";
    case "objectDetails":
      return "Ship Details Information";
    case "notificationList":
      return "Notification List Information";
    case "notificationDetails":
      return "Notification Details Information";
    case "settings":
      return "Settings Information";
    case "errors":
      return "Error List Information";
    case "none":
      return "Map Information";
    default: {
      return "";
    }
  }
}

export default InformationPopUp;
