react_build:
  stage: build
  image: node:lts
  needs: []
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build


react_tests:
  stage: test
  image: node:lts
  needs: ["react_build"]
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run test:ci
  coverage: /All files[^|]*\|[^|]*\|[^|]*\s+([\d\.]+)/

react_linter:
  stage: code_quality
  image: node:lts
  needs: ["react_build"]
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run lint

react_prettier_checks:
  stage: code_quality
  image: node:lts
  needs: ["react_build"]
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run prettier:check
