.react_job_template:
  image: node:20.13.1
  needs: []
  before_script:
    - cd frontend
    - npm ci

react_tests:
  extends: [.react_job_template]
  stage: test
  script:
    - npm run test:ci
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - frontend/junit.xml
      - frontend/coverage/cobertura-coverage.xml
      - frontend/coverage/lcov-report/index.html
    reports:
      junit: frontend/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: frontend/coverage/cobertura-coverage.xml

react_linter:
  extends: [.react_job_template]
  stage: code_quality
  script:
    - npm run lint

react_prettier_checks:
  extends: [.react_job_template]
  stage: code_quality
  script:
    - npm run prettier:check

react_statement_coverage:
  extends: [.react_job_template]
  stage: collect_coverage
  needs: ["react_tests"]
  script:
    - cat coverage/lcov-report/index.html | head -n26 | tail -n1 | grep -Po "\d+(\.\d+)?"
  coverage: /\d+\.\d+/

react_branch_coverage:
  extends: [.react_job_template]
  stage: collect_coverage
  needs: ["react_tests"]
  script:
    - cat coverage/lcov-report/index.html | head -n33 | tail -n1 | grep -Po "\d+(\.\d+)?"
  coverage: /\d+\.\d+/