.stress_tester_job_template:
  image: gradle:8.7.0-jdk17
  needs: []
  before_script:
    - cd stress-tester

stress_tester_checkstyle:
  extends: [.stress_tester_job_template]
  stage: code_quality
  script:
    - gradle checkstyleMain

stress_tester_pmd_static_analysis:
  extends: [.stress_tester_job_template]
  stage: code_quality
  script:
    - gradle pmdMain
