workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "dev"

stages:
  - build
  - test
  - code_quality

include:
  - local: frontend/.gitlab-ci.yml
  - local: simulator/.gitlab-ci.yml
  - local: backend/.gitlab-ci.yml

