backend_build:
  stage: build
  image: gradle:7.6.0-jdk17
  needs: []
  before_script:
    - cd backend
    - chmod +x ./gradlew
  script:
    - ./gradlew assemble

backend_tests:
  stage: test
  image: gradle:7.6.0-jdk17
  needs: ["backend_build"]
  before_script:
    - cd backend
    - chmod +x ./gradlew
  script:
    - ./gradlew test jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/

backend_mutation_testing:
  stage: test
  image: gradle:7.6.0-jdk17
  needs: ["backend_tests"]
  before_script:
    - cd backend
    - chmod +x ./gradlew
  script:
    - ./gradlew pitest
    - cat build/reports/pitest/index.html | head -n25 | tail -n1 | grep -Po "([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/

backend_checkstyle:
  stage: code_quality
  image: gradle:7.6.0-jdk17
  needs: ["backend_build"]
  before_script:
    - cd backend
    - chmod +x ./gradlew
  script:
    - ./gradlew checkstyleMain

backend_pmd_static_analysis:
  stage: code_quality
  image: gradle:7.6.0-jdk17
  needs: ["backend_build"]
  before_script:
    - cd simulator
    - chmod +x ./gradlew
  script:
    - ./gradlew pmdMain
