.backend_job_template:
  image: gradle:8.7.0-jdk17
  needs: []
  before_script:
    - cd backend

backend_tests:
  extends: [.backend_job_template]
  stage: test
  script:
    - gradle test jacocoTestReport
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - backend/build/test-results/test/**/TEST-*.xml
      - backend/build/reports/jacoco/test/cobertura-jacocoTestReport.xml
      - backend/build/reports/jacoco/test/html/index.html
    reports:
      junit: backend/build/test-results/test/**/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/build/reports/jacoco/test/cobertura-jacocoTestReport.xml


backend_mutation_testing:
  extends: [.backend_job_template]
  stage: test
  script:
    - gradle pitest
    - cat build/reports/pitest/index.html | head -n25 | tail -n1 | grep -Po "([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/

backend_checkstyle:
  extends: [.backend_job_template]
  stage: code_quality
  script:
    - gradle checkstyleMain

backend_pmd_static_analysis:
  extends: [.backend_job_template]
  stage: code_quality
  script:
    - gradle pmdMain

backend_statement_coverage:
  extends: [.backend_job_template]
  stage: collect_coverage
  needs: ["backend_tests"]
  script:
    - cat build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/

backend_branch_coverage:
  extends: [.backend_job_template]
  stage: collect_coverage
  needs: ["backend_tests"]
  script:
    - cat build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/