ALTER TABLE NOTIFICATION ALTER COLUMN ANOMALY_INFORMATION BINARY VARYING(1024);
ALTER TABLE NOTIFICATION ALTER COLUMN AIS_SIGNAL BINARY VARYING(1024);ALTER TABLE NOTIFICATION ALTER COLUMN ANOMALY_INFORMATION BINARY VARYING(1024);
