CREATE TABLE IF NOT EXISTS notification (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SHIP_ID BIGINT NOT NULL,
    ANOMALY_INFORMATION BINARY VARYING(1024),
    AIS_SIGNAL BINARY VARYING(1024)
    -- Add other columns as needed
    );