export const informationText = (page: string) => {
  switch (page) {
    case "anomalyList":
      return `
       The Anomaly List displays real-time locations of vessels on a map. Each entry in the scrollable 
       list includes the vessel's type (represented by an icon), the last three digits of the vessel's ID,
       its current anomaly score, and the time since the most recent AIS signal. You can click 
       on an entry for more detailed information. Also, once the entry is clicked, a corresponding
       ship is centered on the map. Moreover, by clicking the filter icon, you can change
       the anomaly score threshold to filter out vessels with scores below the threshold.
       Lastly, you can click the close button or the ship icon in the menu to exit the Anomaly List.
        `;
    case "objectDetails":
      return `
        The Object Details window displays real-time information for a specific vessel.
        The ship's ID is shown at the top. Below the ID, you can choose the 
        type of information you want to see by selecting from the menu. You can 
        view the current Anomaly Information data, current AIS data, all notifications
        related to the displayed vessel, and an interactive plot showing the vessel's
        anomaly score over time.

        Additionally, once the information was displayed, a vessel that corresponds to the displayed 
        information was centered in a map, and its past trajectory displayed. To exit the detailed 
        information window, you can click the arrow in the top-left corner.
        `;
    case "notificationList":
      return `
      The Notification List window displays a history of all notifications that have been
      sent. A notification is sent when a vessel becomes anomalous, meaning its anomaly
      score exceeds a specified threshold. Each entry in the scrollable list corresponds
      to a particular notification and contains, from left to right, a visual indicator
      of whether the notification has been read (orange bells means unread, white bells
      means read), the type of vessel that received the notification (indicated by an icon),
      the last three digits of its ID, and the time and date when the notification was received.

      You can click on a notification to get more detailed information about it, and also center the 
      corresponding ship on the map; notification is then automatically marked as read. 
      Additionally, you can mark all notifications as read by clicking the check button 
      in the top right corner. Finally, you can close the notification list by clicking the 
      close button in the top left corner or a bell icon in the menu list.
      `;
    case "notificationDetails":
      return `
      The Notification Details window displays information about a specific notification. 
      At the top, you can see the ID of the notification and right below it, the ship's ID is shown. 
      Below this, there is a two-choice menu. You can click on the desired option to view either the 
      anomaly information corresponding to the ship's anomaly at the time the notification was sent, or 
      view the AIS information at the time of the notification.

      To exit the Notification Details window, you can click on the arrow in the top-left corner.
      `;
    case "errors":
      return `
      The Error List displays all error notifications generated by the system during
      execution. This list is for internal use only and provides information about
      issues within the system. The notification list contains three types of entries:
      errors (marked with a red icon), warnings (marked with a yellow icon), and 
      information (marked with an information icon). Errors are the most critical, 
      indicating issues that require immediate attention. Warnings are less severe 
      and are triggered by unexpected events that are not highly detrimental to the
      system. Information notifications provide useful information for the operator,
      such as when the server returns an empty list of ships.

      Each entry in the scrollable list of notifications includes, from left to 
      right, an icon corresponding to the type of error or notification, a brief
      description, and a bin icon that, when clicked, deletes the notification.
      You can click an entry to mark it as read. Additionally, you can mark all notifications 
      as read by clicking a button in the top-right corner. 
      Finally, you can close the error list window by clicking the exit button 
      in the top-left corner, or a corresponding warning icon in the menu.
      `;
    case "none":
      return `
      The map displays real-time ship locations based on their AIS data. Each ship's 
      color indicates its anomaly score, with greener colors representing less 
      anomalous ships and redder colors representing more anomalous ships. You 
      can use the mouse to zoom in and move around the map. You can also click on a ship's 
      visual indicator to get more detailed information about its anomaly 
      score, AIS data, and notifications specific to that ship.

      Additionally, the clickable menu on the right-hand side includes the following 
      options from top to bottom: full anomaly list of all ships, notification history, 
      settings, and application errors.
      
      Finally, you can see brief information about a ship when hovering the mouse over the ship's visual indicator.
      `;
    default: {
      return "";
    }
  }
};
